web:
  port: 8080
  host: "localhost"
db:
  dsn: "/tmp/listen-tube-test/test.db"
  driver: "sqlite"
subscriber:
  fetcher:
    enable: true
    fetch_interval_seconds: 30
  downloader:
    enable: true
    base_path: "/tmp/listen-tube-test/listen-tube/"
    yt_dlp_link: "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux"
    download_interval_seconds: 120