web:
  port: 8080
  host: "0.0.0.0"

db:
  dsn: "/tmp/listen-demo/listen-tube.db"
  driver: "sqlite"

downloader:
  bin_uri: "/tmp/listen-demo/listen-tube/.bin/yt-dlp"
  bin_url: "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux"
  base_path: "/tmp/listen-demo/listen-tube/"
